app_accounts/urls.py
from django.urls import path
from . import views

app_name = 'app_accounts'

urlpatterns = [
    path('', views.profile, name='profile'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'my_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('course_detail/<int:id>', views.course_detail, name='course_detail'),
    path('register-course/<int:course_id>', views.register_course, name='register-course'),

]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('profile/', include(('app_accounts.urls', 'app_accounts'), namespace='app_accounts')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},
         name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_accounts/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth import get_user_model
from my_app.models import Course
User = get_user_model()


EDUCATION_TYPE = (
    (1, 'سیکل'),
    (2, ' دیپلم  '),
    (3, ' کاردانی '),
    (4, 'کار شناسی'),
    (5, 'ارشد'),
    (6, 'دکترا'),
)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    _education = models.PositiveSmallIntegerField(choices=EDUCATION_TYPE, null=True)
    phone = models.CharField(max_length=15, null=True)
    # location = models.CharField(max_length=30, blank=True)
    # birth_date = models.DateField(null=True, blank=True)

    @property
    def education(self):
        return dict(EDUCATION_TYPE)[self._education]

    @education.setter
    def education(self, education_type):
        reversed_types = {v: k for k, v in dict(EDUCATION_TYPE).items()}
        self._education = reversed_types.get(education_type)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class RegistredCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return '%s - %s' % (self.user.username, self.course.title)

my_app/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


def course_image_path(instance, filename):
    return instance.title


class Course(models.Model):
    image = models.ImageField(upload_to=course_image_path, null=True)
    altt = models.CharField(max_length=100, null=True)
    title = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)

    def __str__(self):
        return self.title

class CourseSession(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)
    attachment_files = GenericRelation('AttachmentFiles')
    aparat_video = models.TextField(null=True)

    def __str__(self):
        return self.title

class CourseSessionExercise(models.Model):
    coursesession = models.ForeignKey(CourseSession, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100, null=True)
    description = models.TextField(null=True)
    attachment_files = GenericRelation('AttachmentFiles')

    def __str__(self):
        return self.title

class AttachmentFiles(models.Model):
    file = models.FileField(upload_to='attach-files-%y-%m-%d_%H:%M')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()

    def __str__(self):
        return self.content_object.title

app_accounts/views.py
from django.shortcuts import render
from . models import RegistredCourse
from django.contrib.auth.decorators import login_required


@login_required
def profile(request):
    ctx = {}
    ctx['registred_course'] =[rc.course for rc in request.user.registredcourse_set.all()]
    return render(request, 'student-profile.html', ctx)

my_app/views.py
from django.shortcuts import render
from django.urls import reverse
from my_app.models import Course
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required


def index(request):
    ctx = {}
    ctx['courses'] = Course.objects.all()
    return render(request, 'index.html', ctx)


def course_detail(request, id):
    ctx = {}
    ctx['course'] = Course.objects.get(id=id)
    ctx['courses'] = Course.objects.all().exclude(id=id)
    return render(request, 'course_detail.html', ctx)


@login_required
def register_course(request, course_id):
    course = Course.objects.get(id=course_id)
    if course not in [rc.course for rc in request.user.registredcourse_set.all()]:
        request.user.registredcourse_set.create(course=course)
    return HttpResponseRedirect(reverse('app_accounts:profile'))

app_accounts/templates/student-profile.html
 {% extends 'base.html' %}
 {% load static %}
{% block content %}

{% block css %}
{{ block.css }}
<style type="text/css">
.profile-div{
    border-left: 1px solid #d0d3d9;
    padding: 0px; margin: 0px
}
.profile-ul{
    font-size: 18px;
    margin-right:  0px;
    padding: 0px;
}
.profile-li{
     border-bottom: 1px solid #d0d3d9;
     color: #797a7d ;  
    }
.profile-li:hover{
    border-left: 3px solid green;
}
.profile-p{
    font-size: 18px;
    line-height: 25px;
}
</style>
{% endblock css %}
<div class="container" style="margin-top: 90px">
    <h2>حساب کاربری<h2> <hr>
    <div class="row">
        <div class="col-md-3 profile-div">
             <img src="{% static 'images/place/64X64.gif' %}">
                <h4>username</h4>
               <ul class="nav profile-ul">
                <li class="active profile-li"><a href="#">Home</a></li>
                <li><a href="#" class="profile-li" >Menu 1</a></li>
                <li><a href="#" class="profile-li" >Menu 2</a></li>
                <li><a href="#" class="profile-li" style="border-bottom: 0px" >Menu 3</a></li>
                <br><br>
              </ul>
        </div>
        
        <div class="col-md-9">
         <h5>سلام  <span>user name</span></h5>    

            {% for course in registred_course %}
             <dir  class="col-md-6" style="float: left;">
                    {% include "card.html" %}
            </dir>
            {% endfor %}
        </div>
    </div>      
</div>

{% endblock content %}

my_app/templates/base.html
{% load static %}

<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>عنوان محصول :: دریافت شده از وب روبیک</title>
        <link type="text/css" href="{% static 'css/fa-bootstrap.css' %}" rel="stylesheet" />
        {% block css %}
        <style>
            @font-face {
                font-family: Parastoo;
                src: url('{% static "font/Parastoo-FD-WOL.woff" %}');
            }
            @font-face{
                font-family: Vazir-thin;
                src: url('{% static "font/Vazir-Thin-FD-WOL.woff" %}') format('woff'),
                 url('{% static "font/Vazir-Thin-FD-WOL.eot" %}') format('eot'),
                 url('{% static "font/Vazir-Thin-FD-WOL.ttf" %}') format('ttf');
                 
            }
            @font-face{
                font-family: Vazir;
                src: url('{% static "font/Vazir-Medium-FD-WOL.woff" %}') format('woff'),
                url('{% static "font/Vazir-Medium-FD-WOL.eot" %}') format('eot'),
                url('{% static "font/Vazir-Medium-FD-WOL.ttf" %}') format('ttf');
            }
            @font-face{
                font-family: Vazir-bold;
                src: url('{% static "font/Vazir-Bold-FD-WOL.woff" %}') format('woff'),
                url('{% static "font/Vazir-Bold-FD-WOL.eot" %}') format('eot'),
                url('{% static "font/Vazir-Bold-FD-WOL.ttf" %}') format('ttf');
            }
        </style>
        {% endblock css %} 
		<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
		<link type="text/css" href="{% static 'css/style.css' %}" rel="stylesheet" />
		<link href="{% static 'css/jquery-ui.css' %}" rel="stylesheet">

		
	</head>
	<body>
	
			<!--START header-->
			<nav class="navbar navbar-default navbar-fixed-top">
				<div class="container-fluid">
				<div class="navbar-header">
					<a href="{% url 'my_app:index' %}" class="navbar-brand fontbrand">فروشگاه پاسکال</a>
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
				</div>
				<div class="collaps navbar-collapse" id="navbar">
					<ul class="nav navbar-nav">
						<li class="active"><a href="{% url 'my_app:index' %}" class="fontmenu">صفحه اصلی</a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle fontmenu" data-toggle="dropdown">
								پکیجهای آموزشی
								<span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a href="#">ویندوزی </a>
									</li>  
									<li><a href="#">لینوکسی</a></li>
									<li><a href="#">ایران</a></li>
									<li><a href="#">آلمان</a></li>
									</ul>
						</li>
						<li><a href="#" class="fontmenu">آموزشهای رایگان</a></li>
						<li><a href="#" class="fontmenu">تماس با ما</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-left">
						<li><a href="#" id="user-plus">ثبت نام<span class="fa fa-user-plus user-style"></span></a></li>
						<li><a href="{% url 'login' %}" id="sign-in">ورود<span class="fa fa-sign-in sign-style"></span></a></li>
					</ul>
			</nav>
		
		<!--END 
		
		<div>
			<img src="images/pic4.jpg" id="image-headr" alt="inamges">
				
		</div>
		Header-->
		
        


    {% block content %}

    {% endblock content %}

        		<!----Start footer-->
				<div class="footer">
					<div class="col-md-4">
						<h3 class="">نماد اعتماد</h3><br>
						<img src="{% static 'images/place/64X64.gif' %}" alt="vahid" class="box-script">
					</div>

					<div class="col-md-4">
						<h3>لینک های مهم</h3>
						<ol>
							<li><a href="#"></a>google</li>
							<li><a href="#"></a>yahoo</li>
							<li><a href="#"></a>aparat</li>
						</ol>
					</div>

					<div class="col-md-4">
						<a href="#"><i class="fa fa-telegram icon-telegram"></i></a> 
						<a href="#"><i class="fa fa-instagram  icon-instagram"></i></a> 
						<a href="#"><i class="fa fa-television  icon-aparat"></i></a> 
						<form>
							<div class="input-group" style="margin-top: 10px;">
							  <input type="email" class="form-control" placeholder="عضویت در خبرنامه">
							  <div class="input-group-btn">
								<button class="btn btn-default" type="submit" style="margin-left: 10px;">عضویت
								</button>
							  </div>
							</div>
						  </form>
					</div>
					
				</div>
				
				
				
		<!---ENDfooter-->
			

		<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<script src="{% static 'js/jquery-ui.js' %}"></script>
		<script>

		
			
			$(document).ready(function(){
				
				$("#span-aparat").hide();
				$("#span-aparat").slideDown(3000);
				$("#accordion").accordion({
					collapsible : true 
				});
				$("#tel").tooltip();   
				$("#accordion2").accordion({
					collapsible : true 
				});
				

			});
			
		</script>
	
	</body><!-- This template has been downloaded from Webrubik.com -->
	</html>

my_app/templates/card.html
{% block css %}
{{ block.css }}

<style type="text/css">
 div, h5,{
    font-family:Parastoo ;
    font-size: 10px;
 }
</style>
{% endblock css %}

    <a href="{% url 'my_app:course_detail' id=course.id %}">
    <div class="image-product product-hover " style=" padding: 0px; border:1px solid silver;"	 >
        <div>
        <img src="{{ course.image.url }}" alt="{{ course.altt }}"><hr>
        <h5 class="text-product"><b>{{ course.title }} </b></h5>
        <h5 class="text-product"><b><a href="#"> </a></b></h5>
    </a>
        <div class="col-xs-4 w3-block viewpoint" style="font-size: 18px;font-family: Parastoo"><a href="#" class="aviewpoint">جزئیات</a> </div>

        <div style="font-family:Vazir; font-size: 18px "  class="col-xs-4  heart-product" > 123 </div>


        <div style="font-family: Parastoo;font-size: 18px" class="col-xs-4 comment-product">نظرات </div>
        </div>
        <hr>
    </div>



<!--
    {% load sorl_thumbnail %}
    {% thumbnail item.image "100x100" crop="center" as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
    {% endthumbnail %}

    course.description|truncatewords:10
-->

my_app/templates/course_detail.html
{% extends 'base.html'  %}
{% load static %}



{% block content %}
<div style="margin-top: 210px"></div>
<div class="container" style="margin-top: 60px">
  <div class="row">
      <div class="col-md-12">
        <h2>{{ course.description }}</h2>
         <a href="{% url 'my_app:register-course' course_id=course.id %}" class="btn btn-danger">vahid</a>
      </div>
  </div>
</div>

{% endblock content %}

my_app/templates/index.html
{% extends 'base.html'  %}
{% load static %}


{% block content %}


<div class="img-header">
	<img src="{% static 'images/pic4.jpg' %}" class="image-headr">
	<div class="centered"	>بهترین ها آموزش های برنامه نویسی را از ما بخواهید</div>
</div>

		<div class="container">
			<h2 class="h2-h2"><b><span>آخرین</span> <span id="span-red">محصولات</span></b></h2>
			<h5 class="h5-h5">محصول خود را انتخاب کنید</h5>
		</div>
		<!---start card--->
		<div class="container">
			<div class="row">
				
				{% for course in courses %}
				<div class="col-md-4">
					{% include "card.html" %}
					</div>
				{% endfor %}
				
			</div>
		</div>
		<!---end card--->	

		<!--strat aparat-->
			<div class="row row-aparat">
				<div  class="col-aparat">
					<b><span class="span-aparat" id="span-aparat" >می دونستی تو آپارات کلی نمونه ویدئو آپلود کردیم؟</span></b>
					<a href="" class="btn btn-success btn-aparat">آپارات</a>
				</div>
			</div>
		<!--end aparat-->
	

		<div>
			<h2 class="h2-h2"><b><span>پرسش و </span> <span id="span-red">پاسخ</span></b></h2>
			<h5 class="h5-h5">مشاهده سوالات پاسخ داده شده توسط ما</h5>
		</div>
		<!-- start question-->
		<div class="row container" style="margin-bottom: 80px;">
			<div class="col-md-6"> 
				<div id="accordion">
					<h6 style="font-size: 13px;">آیا بعد از خرید، میتوانم محصول خریداری شده را دانلود کنم؟</h6>
					<div>
						<p>
							بله – محصولات سایت  ما هم به صورت دی وی دی هستند و هم به صورت دانلودی که لینک دانلود برای شما ایمیل میشود
						</p>
					</div>
					<h6 style="font-size: 13px;">آیا این آموزش ها پیشنیاز میخوان؟</h6>
					<div>
						<p>
							به هیچ وجه، تنها پیش نیاز علاقه شما است.
					</div>
					<h6 style="font-size: 13px;">در صورت بروز مشکل چه کار کنم؟</h6>
					<div>
						<p>
							فقط کافیست از طریق راهای ارتباطی موجود با ما در تماس باشید
						</p>
					</div>
				</div>
			</div>
			
						
			<div class="col-md-6">
				<div id="accordion2">
					<h5 class="accordion" style="font-size: 13px;">آیا در کنار فیلم های آموزشی، ابزارهای مورد نیاز وجود دارند؟</h5>
					<div>
						<p>
							بله – در صورتی که در آموزش ها از فایل و یا برنامه ایی استفاده کرده باشیم، درون پکیج قرار داده شده است.
						</p>
					</div>
					<h5 class="accordion" style="font-size: 13px;">آیا آموزشهای اراءه شده در سایت فارسی و تصویری هستند؟</h5>
					<div>
						<p>
							به تمام آموزش ها سایت با کیفیت بالا و به زبان فارسی ارءه شده اند
						</p>
					</div>
					<h5 class="accordion" style="font-size: 13px;">آیا آموزش های سایت پشتیبانی هم دارند</h5>
					<div>
						<p>
							بله ، ما با افتخار در کنار شما هستیم
						</p>
					</div>
				</div>
			</div>
		</div>
		<!--end question-->

{% endblock content %}